apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-servicemonitor
  labels:
    #release: prometheus-stack  # ajuste conforme o nome do seu Helm release
    app: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  namespaceSelector:
    matchNames:
      - default  # ou o namespace onde está o Kafka
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
      scheme: http
      honorLabels: true
