apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-jmx-config
data:
  config.yml: |
    hostPort: localhost:9999
    lowercaseOutputName: true
    labels:
      strimzi_io_cluster: "teste"
    rules:
      # Métricas de tópico
      - pattern: kafka.server<type=(.+), name=(.+)><>(Value|Count|Mean|Max|Min|OneMinuteRate|FiveMinuteRate|FifteenMinuteRate)
        name: kafka_server_$1_$2
        type: GAUGE   
      # Métricas de replicação
      - pattern: kafka.cluster<type=(.+), name=(.+)><>(Value|Count|Mean|Max|Min|OneMinuteRate|FiveMinuteRate|FifteenMinuteRate)
        name: kafka_cluster_$1_$2
        type: GAUGE
      # Métricas de log
      - pattern: kafka.log<type=(.+), name=(.+)><>(Value|Count|Mean|Max|Min|OneMinuteRate|FiveMinuteRate|FifteenMinuteRate)
        name: kafka_log_$1_$2
        type: GAUGE
      # Métricas de controlador
      - pattern: kafka.controller<type=(.+), name=(.+)><>(Value|Count|Mean|Max|Min|OneMinuteRate|FiveMinuteRate|FifteenMinuteRate)
        name: kafka_controller_$1_$2
        type: GAUGE
      # Métricas de rede
      - pattern: kafka.network<type=(.+), name=(.+)><>(Value|Count|Mean|Max|Min|OneMinuteRate|FiveMinuteRate|FifteenMinuteRate)
        name: kafka_network_$1_$2
        type: GAUGE
      # Métricas de requisição
      - pattern: kafka.request<type=(.+), name=(.+)><>(Value|Count|Mean|Max|Min|OneMinuteRate|FiveMinuteRate|FifteenMinuteRate)
        name: kafka_request_$1_$2
        type: GAUGE
      # Métricas específicas
      - pattern: kafka.network<type=(.+), name=(.+)><>
        name: kafka_network_$1_$2
        type: GAUGE
      - pattern: kafka.server<type=BrokerTopicMetrics, name=MessagesInPerSec, topic=(.+)>
        name: kafka_server_brokertopicmetrics_messagesinpersec_count
        type: COUNTER
        labels:
          topic: "$1"
        attr:
          Count: count
