apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
        prometheus.io/scrape: "true"
        prometheus.io/port: "9404"
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.5.0
          command: ["bash", "-c", "unset KAFKA_PORT; /etc/confluent/docker/run"]
          ports:
            - containerPort: 9092
              name: kafka
            - containerPort: 9404
              name: metrics
          env:
            - name: PORT
              value: ""
            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_NODE_ID
              value: "1"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@localhost:9093"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka:9092"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_LOG_DIRS
              value: "/tmp/kraft-combined-logs"
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
            - name: CLUSTER_ID
              value: "5L6g3nShT-eMCtK--X86sw"
            - name: KAFKA_JMX_PORT
              value: "9999"
            - name: JMX_PORT
              value: "9999"
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "2Gi"
        - name: jmx-exporter
          image: bitnami/jmx-exporter:latest
          ports:
            - containerPort: 9404
              name: metrics
          args:
            - "9404"
            - "/config/config.yml"
          volumeMounts:
            - name: jmx-config
              mountPath: /config
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "256Mi"
      volumes:
        - name: jmx-config
          configMap:
            name: kafka-jmx-config
