apiVersion: apps/v1
kind: Deployment
metadata: 
  labels:
    app: nginx-deployment2
  name: nginx-deployment2
  namespace: giropops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-deployment2
  strategy: {}
  template: 
    metadata:
      labels:
        app: nginx-deployment2
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: 
           limits:
             cpu: "0.5"
             memory: 256Mi
           requests:
             cpu: "0.3"
             memory: 64Mi
